Pizzeria/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizzas/urls.py
from django.urls import path


from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizza', views.pizza, name='pizza'),
    path('pizza/<int:piz_id>/', views.piz, name='piz'),
    path('new_comment/<int:piz_id>/', views.new_comment, name='new_comment'),
]

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
        
class Topping(models.Model):
    piz = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Toppings'

    def __str__(self):
        return self.name

class Comment(models.Model):
    piz = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Comments'

    def __str__(self):
        return self.name

class Image(models.Model):
    piz = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    image = models.ImageField()

pizzas/forms.py
from django import forms

from .models import Pizza, Comment

class TopicForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name']
        labels = {'name':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name']
        labels = {'name': ""}

pizzas/views.py
from django.shortcuts import render, redirect
from .forms import TopicForm, EntryForm
from .models import Pizza, Topping, Image

# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html') # point to which template to use

def pizza(request):
    pizza = Pizza.objects.order_by('date_added')

    context = {'pizza':pizza}

    return render(request, 'pizzas/pizza.html', context)


def piz(request, piz_id):
    piz = Pizza.objects.get(id=piz_id)

    topping = piz.topping_set.all()
    comment = piz.comment_set.all()
    image  = Image.objects.get(piz=piz)
    print(image)

    context = {'piz':piz, 'topping':topping, 'comment':comment, 'image':image}

    return render(request, 'pizzas/piz.html', context)

def new_comment(request, piz_id):
    piz = Pizza.objects.get(id=piz_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data = request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.piz = piz
            new_comment.save()

            return redirect('pizzas:piz', piz_id=piz_id)

    context = {'form':form, 'piz':piz}
    return render(request, 'pizzas/new_comment.html', context)



'''
    <img src="{% static 'pizzas/meat lover.jpg' %}" alt="Pizzeria" width="700" height="350">

    <img src="{% static 'pizzas/hawaiian.jpg' %}" alt="Pizzeria" width="700" height="350">
    '''

pizzas/templates/pizzas/base.html
{% load bootstrap4 %} 

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %} 
    {% bootstrap_javascript jquery='full' %} 
        
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'pizzas:index'%}">
            Pizzeria</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pizzas:pizza'%}">
                        Pizzas</a></li>
            </ul>

        </div>

    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div class="pb-2 mb-2 border-bottom">
            {% block content %}{% endblock content %}
        </div>
    </main>


</body>


</html>

pizzas/templates/pizzas/comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>
    Add a new comment:
</p>

<form action="{% url 'pizzas:comment' %}" method='post'>
    {% csrf_token%}
    {{form.as_p}}
    <button name="submit">Add comment</button>
</form>



{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% load static %}
{% block page_header %}

<div class="jumbotron">
    <h1 class="display-3">Pizzeria</h1>

    <p class="lead">Know the toppings for your favorite Pizza and make some comments!!!</p>
    <a class="btn btn-lg btn-primary" href="{% url 'pizzas:pizza' %}"
        role="button">Pizzas &raquo;</a>
</div>

<img src="{% static 'pizzas/Piz.jpg' %}" alt="Pizzeria" width="800" height="400">


{% endblock page_header %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>
    Add a new comment:
</p>

<form action="{% url 'pizzas:new_comment' piz.id %}" method='post'>
    {% csrf_token%}
    {{form.as_p}}
    <button name="submit">Add comment</button>
</form>



{% endblock content %}

pizzas/templates/pizzas/piz.html
{% extends "pizzas/base.html" %}
{% load static %}
{% block page_header %}
<h3>{{ piz }}</h3>
{% endblock page_header %}

{% block content %}

{% for t in topping %}

    <div class="card mb-3">
        <h4 class="card-header">
            <p>Toppings</p>
        </h4>
        <div class="card-body">
            {{ t.name | linebreaks}}
            {{ t.date_added | date:'M d,Y H:i' }}
        </div>
    </div>
    {% empty %}
        {% endfor %}


        <ul>
            <li><h3>
                <img src="{{ image.image.url }}" alt="Pizzeria" width="550" height="350">
            </h3></li>
        </ul>


    <p>
        <a href="{% url 'pizzas:new_comment' piz.id %}">Add a new comment</a>
    </p>


{% for c in comment %}

    <div class="card mb-3">
        <h4 class="card-header">
            {{ c.date_added | date:'M d,Y H:i' }}
        </h4>
        <div class="card-body">
            {{ c.name | linebreaks}}
        </div>
    </div>
    {% empty %}
        <p>There are no comments for this pizza yet.</p>
        {% endfor %}



{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block page_header %}
<h1>Pizzas</h1>
{% endblock page_header %}

{% block content %}

<ul>
    {% for p in pizza %}

    <li>
        <h3>
            <a href="{% url 'pizzas:piz' p.id %}">{{ p }}</a>
        </h3>
    </li>
    {% empty %}
    <li><h3>No pizzas have been added yet.</h3></li>
    {% endfor %}
</ul>


{% endblock content %}